### PR TITLE
CASMINST-5556 - Remove outdated and unreferenced NTP procedure

### PR DESCRIPTION
**Pull request by spillerc-hpe**
# Description

This procedure is no longer required. NTP is configured on the PIT by the `pit-init.sh` script and the other NCNs have NTP configured by cloud-init.

The [Configure_NTP_on_NCNs.md](https://github.com/Cray-HPE/docs-csm/blob/release/1.6/operations/node_management/Configure_NTP_on_NCNs.md) procedure covers reconfiguring the NTP service.

# Checklist

- [X] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [X] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [X] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

### CODE REVIEW

**Review by nrockershousen — APPROVED** [review]

**Review by rustydb — APPROVED** [review]

**Comment by rustydb** [comment]
Please fix the ToC for the deleted page: https://github.com/Cray-HPE/docs-csm/actions/runs/9888619758/job/27312940310?pr=5223#step:7:317

**Pull request merged**
