### PR TITLE
SKERN-9232: Update product name references

### PR DESCRIPTION
**Pull request by esoucy-hpe**
# Description
This is a cherry-pick of bbd77cee0a9f3a1610835f32f7a9a24ccdcc3f2c from PR https://github.com/Cray-HPE/docs-csm/pull/4622 release/1.6 which updated COS Base and USS product name references.

# Checklist
- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

### CODE REVIEW

**Comment by deantroe** [comment]
There are other references to COS/cos in the document, but in general I think that is OK as COS is still a product, it is just made up of both USS and COS Base content now.  Having said that, we do need to change all references to cos-config-management to uss-config-management as the former will no longer exist.

**Review by deantroe — APPROVED** [review]
Looks good to me.  I am a bit surprised that somehow previous commits were able to introduce code that does not pass the style check...at least that is what I am assuming happened for the formatting changes you are making unrelated to COS/USS naming.  If anyone from CSM is concerned about this, please speak up.

**Comment by safoote** [comment]
Superb style

**Review by rustydb — APPROVED** [review]

**Pull request merged**
