### PR TITLE
CASMCMS-8720: Update argo workflows for CFS v3 and paging

### PR DESCRIPTION
**Pull request by mtupitsyn**
# Description

Follow up after #4283 - accommodate change in `/apis/cfs/v3/components` response format in argo workflows.

# Checklist
- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

### CODE REVIEW

**Comment by rbak-hpe** [comment]
This does effectively address the upgrade issue between CFS v2 and v3, but it's strange to me that you're calling the "list components" endpoint repeatedly for a single component.  Why not just describe the component and check its status? This works, its just less efficient on the CFS side.

**Comment by mtupitsyn** [comment]
> This does effectively address the upgrade issue between CFS v2 and v3, but it's strange to me that you're calling the "list components" endpoint repeatedly for a single component. Why not just describe the component and check its status? This works, its just less efficient on the CFS side.

In this PR, I only update `jq` expression to match new response format. I did not intend to rewrite logic of this wait condition.

**Review by mharding-hpe — APPROVED** [review]

**Comment by mharding-hpe** [comment]
Theoretically there could be an issue here if the CFS query being made returns more results than will fit in a single response, but I am assuming from the context that the query is limited to a small-ish number of xnames.

**Comment by mharding-hpe** [comment]
> This does effectively address the upgrade issue between CFS v2 and v3, but it's strange to me that you're calling the "list components" endpoint repeatedly for a single component. Why not just describe the component and check its status? This works, its just less efficient on the CFS side.

Looking at this code, I think it was based on the code from the venerable [`apply_csm_configuration`](https://github.com/Cray-HPE/docs-csm/blob/92c0a77a05aa7511b0ed887889cdad2d2f6a235a/scripts/operations/configuration/apply_csm_configuration.sh#L308) shell script. In that script, it uses similar logic, only it is doing so for all of the NCNs. I am guessing that whoever originally authored these workflows just mimicked that without realizing that it is not the best way to do it when dealing with a single specific node.

**Review by rustydb — APPROVED** [review]

**Pull request merged**
