### PR TITLE
CASMTRIAGE-4674: fix the docs-csm rpm link

### PR DESCRIPTION
**Pull request by bo-quan**
# Description

1.4 upgrade instructions has a reference of docs-csm rpm link that points to sp2, which should be changed to sp3.

# Checklist Before Merging

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

### CODE REVIEW

**Review by bklei — APPROVED** [review]

**Comment by johren-hpe** [comment]
There are other references to the docs-csm rpm location:
```
operations/package_repository_management/Manage_Repositories_with_Nexus.md:https://packages.local/repository/csm-sle-15sp2/noarch/docs-csm-1.7.4-20210206165423_2fae6fa.noarch.rpm
update_product_stream/README.md:   rpm -Uvh --force https://artifactory.algol60.net/artifactory/csm-rpms/hpe/stable/sle-15sp2/docs-csm/1.4/noarch/docs-csm-latest.noarch.rpm
update_product_stream/README.md:   wget https://artifactory.algol60.net/artifactory/csm-rpms/hpe/stable/sle-15sp2/docs-csm/1.4/noarch/docs-csm-latest.noarch.rpm -O docs-csm-latest.noarch.rpm
update_product_stream/index.md:   rpm -Uvh --force https://artifactory.algol60.net/artifactory/csm-rpms/hpe/stable/sle-15sp2/docs-csm/1.4/noarch/docs-csm-latest.noarch.rpm
update_product_stream/index.md:   wget https://artifactory.algol60.net/artifactory/csm-rpms/hpe/stable/sle-15sp2/docs-csm/1.4/noarch/docs-csm-latest.noarch.rpm -O docs-csm-latest.noarch.rpm
upgrade/Stage_0_Prerequisites.md:      wget https://artifactory.algol60.net/artifactory/csm-rpms/hpe/stable/sle-15sp2/docs-csm/1.4/noarch/docs-csm-latest.noarch.rpm \
upgrade/scripts/upgrade/prerequisites.sh:    cp /root/docs-csm-latest.noarch.rpm "${CSM_ARTI_DIR}/rpm/cray/csm/sle-15sp2/"
```

**Comment by johren-hpe** [comment]
This has some overlap with CASMINST-5517 which will need to change (very soon) these (and other) references to use https://release.algol60.net/ instead of artifactory.

**Comment by bo-quan** [comment]
Thank you @johren-hpe for your comments. I amended it with additional references to sp2 for docs-csm. As fixing [CASMINST-5517](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5517) is more involved, we can make this incremental change to unblock 1.4 upgrade as other people are likely to run into this again within the next few days.

**Comment by johren-hpe** [comment]
Yep, your call.   I was only thinking that we could use 
```
https://release.algol60.net/csm-1.4/docs-csm/docs-csm-latest.rpm
```
instead of
```
https://artifactory.algol60.net/artifactory/csm-rpms/hpe/stable/sle-15sp3/docs-csm/1.4/noarch/docs-csm-latest.noarch.rpm
```

In the changes that you made to start using the new release location and get a jump start on one part of CASMINST-5517.   I didn't intend to imply that we would do all of CASMINST-5517 in this PR.

**Review by rustydb — APPROVED** [review]

**Comment by bo-quan** [comment]
> Yep, your call. I was only thinking that we could use
> 
> ```
> https://release.algol60.net/csm-1.4/docs-csm/docs-csm-latest.rpm
> ```
> 
> instead of
> 
> ```
> https://artifactory.algol60.net/artifactory/csm-rpms/hpe/stable/sle-15sp3/docs-csm/1.4/noarch/docs-csm-latest.noarch.rpm
> ```
> 
> In the changes that you made to start using the new release location and get a jump start on one part of [CASMINST-5517](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5517). I didn't intend to imply that we would do all of [CASMINST-5517](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5517) in this PR.

Good point. I made the changes and pushed them to the branch, but the PR had been merged a few minutes ahead of my changes.

**Pull request merged**
