### PR TITLE
0.9.6 Patch

### PR DESCRIPTION
**Pull request by SeanWallace**
First draft of 0.9.6 doc containing information mostly specific to the application of the Unbound fix.

### CODE REVIEW

**Review by bo-quan — COMMENTED** [review]
@SeanWallace Not sure if you're aware, we had a release/0.9 branch to hold the 0.9 upgrade instructions at https://github.com/Cray-HPE/docs-csm/blob/release/0.9/upgrade/0.9 . Does it make more sense to use release/0.9 branch for this commit?

**Comment by SeanWallace** [comment]
> @SeanWallace Not sure if you're aware, we had a release/0.9 branch to hold the 0.9 upgrade instructions at https://github.com/Cray-HPE/docs-csm/blob/release/0.9/upgrade/0.9 . Does it make more sense to use release/0.9 branch for this commit?

Yep, good catch, that is the branch this should target. Thanks!

**Comment by bo-quan** [comment]
To be consistent with previous two upgrades (0.9.4, and 0.9.5), I suggest to rename it as README.md under a subdir csm-0.9.6 instead.

**Comment by SeanWallace** [comment]
> Thank you Sean for changing the release target. To be consistent with previous two upgrades (0.9.4, and 0.9.5), I suggest to rename it as README.md under a subdir csm-0.9.6 instead.

Well consistency seems to suggest that if there is only one README file and no other accompanying files then it's not under a subdir but rather under the main 0.9 folder with the full name. But it doesn't matter to me, I can move it if need be.

**Comment by bo-quan** [comment]
There will be multiple changes for 0.9.6, so please move it under a directory to avoid refactoring in subsequent check-ins.

**Review by bklei — APPROVED** [review]

**Pull request merged**
