### PR TITLE
CASMNET-1791/CASMNET-1940 - ncn_add_pre-req.py fixes

### PR DESCRIPTION
**Pull request by spillerc-hpe**
# Description

* [CASMNET-1791](https://jira-pro.it.hpe.com:8443/browse/CASMNET-1791) - Update `ncn_add_pre-req.py` script to actually remove the HSM ethernetInterfaces record instead of just printing that it's going to do it.
* [CASMNET-1940](https://jira-pro.it.hpe.com:8443/browse/CASMNET-1940) - Add a check to `ncn_add_pre-req.py` so it aborts if the calculated `DHCPStart` value equals or exceeds `DHCPEnd` so an invalid configuration can't be uploaded to SLS which breaks Kea. 

# Checklist

- [X] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [X] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [X] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

### CODE REVIEW

**Comment by spillerc-hpe** [comment]
This was tested during the add of ncn-w005 on surtur. Verified that the DHCP reservation for the UAN was deleted from SMD ethernetInterfaces.

Also verified that the new check for the DHCP pool range works.
```bash
ncn-m001:~/cspiller # ./ncn_add_pre-req.py
The prerequisite script prepares adding NCNs by adjusting SLS network configurations.



Please enter answer as an integer.
How many NCNs would you like to add? Do not include NCNs to be removed or moved.
30

You are about to make DESTRUCTIVE changes to the system and will need to restart DVS.

If you are sure you want to proceed.  Please type: PROCEED

If you want to stop.  Type: exit or press ctrl-c

PROCEED

Checking HMN.
last_reserved_ip: 10.254.1.24    start_dhcp_pool:10.254.1.26
The space between last_reserved_ip and start_dhcp_pool is 2 IP.

There is not enough static IP space to add an NCN.Adjusting DHCP pool start.
{'HMN': {'10.254.1.61', '10.254.1.33', '10.254.1.41', '10.254.1.32', '10.254.1.62', '10.254.1.26', '10.254.1.39', '10.254.1.40', '10.254.1.83', '10.254.1.68', '10.254.1.50', '10.254.1.28', '10.254.1.84', '10.254.1.78', '10.254.1.54', '10.254.1.29', '10.254.1.46', '10.254.1.36', '10.254.1.37', '10.254.1.27', '10.254.1.30', '10.254.1.42', '10.254.1.56', '10.254.1.57', '10.254.1.67', '10.254.1.71', '10.254.1.58', '10.254.1.59', '10.254.1.74', '10.254.1.48', '10.254.1.38', '10.254.1.49', '10.254.1.60', '10.254.1.75', '10.254.1.82', '10.254.1.25', '10.254.1.66', '10.254.1.47', '10.254.1.43', '10.254.1.52', '10.254.1.51', '10.254.1.73', '10.254.1.63', '10.254.1.79', '10.254.1.35', '10.254.1.34', '10.254.1.55', '10.254.1.80', '10.254.1.31', '10.254.1.53', '10.254.1.69', '10.254.1.44', '10.254.1.72', '10.254.1.77', '10.254.1.45', '10.254.1.65', '10.254.1.76', '10.254.1.81', '10.254.1.70', '10.254.1.64'}}

add_ncn_count: 30
ip_dhcp_pool_start:
{'HMN': '10.254.1.26', 'MTL': '10.1.1.14', 'CHN': '10.102.193.210', 'CMN': '10.102.193.31', 'NMN': '10.252.1.16'}
new_ip_dhcp_pool_start:
{'HMN': '10.254.1.87'}


Checking CMN.
last_reserved_ip: 10.102.193.29    start_dhcp_pool:10.102.193.31
The space between last_reserved_ip and start_dhcp_pool is 2 IP.

There is not enough static IP space to add an NCN.Adjusting DHCP pool start.
2023-12-04 09:21:34,278 - __main__ - ERROR - New CMN DHCPStart value 10.102.193.62 exceeds available DHCP pool capacity.
```

**Review by rustydb — APPROVED** [review]

**Pull request merged**
