### PR TITLE
CASMPET-5935 : DOCS: "Copy the database dump file to the postgres member " results error

### PR DESCRIPTION
**Pull request by kimjensen-hpe**
Fixes CASMPET-5935

# Description

Adds steps to rename the .psql file to workaround a `kubectl cp` bug
Other minor cleanup
Removes capsules which was deprecated in csm 1.2
Replaces python scripts to list and download s3 files with `cray artifacts`

TBD : Backport to release/1.3 and release/1.2

# Checklist Before Merging

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

### CODE REVIEW

**Review by rgross727 — APPROVED** [review]

**Comment by kimjensen-hpe** [comment]
backport release/1.2

**Pull request merged**
