### PR TITLE
CASMINST-5643 DOCS: add stage "Re-add Storage Node to Ceph" in storage rebuild procedure

### PR DESCRIPTION
**Pull request by leliasen-hpe**
# Description

Add stage "Re-add Storage Node to Ceph" in storage rebuild procedure. Two stages were missing in the storage node rebuild procedure. This changes adds those needed stages back in.

# Checklist Before Merging

- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

### CODE REVIEW

**Review by kimjensen-hpe — APPROVED** [review]

**Comment by leliasen-hpe** [comment]
I have closed the previous backport branch because it was out of date. I am creating a new backport which will include the latest changes.

/backport release/1.3

**Review by bklei — APPROVED** [review]

**Review by kimjensen-hpe — APPROVED** [review]

**Pull request merged**
