### PR TITLE
CASMNET-2028 | Transceiver and cable guide for management network

### PR DESCRIPTION
**Pull request by kosonenj**
# Description

Transceiver and cable guide for management network

# Checklist Before Merging

- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

### CODE REVIEW

**Comment by gbaker-hpe** [comment]
I this the transceiver guide looks really good.  I left a few comments but that information is great and I think it will really help.

I think we should add a second page that better highlights the PoR switch connections and then points the user to the right cables.  For example, We have different PoR scenarios where we have spines and leafs that connect, and various other combinations.  It would be good to include a diagram of an Aruba spine (with model) to an Aruba Leaf (with model) and then list the cables that would work for those runs.

**Review by gbaker-hpe — CHANGES_REQUESTED** [review]
Let's get those hard tabs the linter is calling out fixed.  Also, Rusty is updating the linter CLI versions which should allow tests to be skipped with inline comments which will address the header linting failures.

**Review by gbaker-hpe — APPROVED** [review]

**Review by kosonenj — COMMENTED** [review]
ready to merge

**Comment by gbaker-hpe** [comment]
This has been discussed in Slack by many people and it's good to go.

**Review by rustydb — APPROVED** [review]

**Pull request merged**
