### PR TITLE
CASMINST-5657 Add common WorkflowTemplate to sync secret to Argo namespace

### PR DESCRIPTION
**Pull request by Srinivas-Anand-HPE**
## Summary and Scope

Create common WorkflowTemplate to sync secret to Argo namespace by refactorin nexus prerequisites step out into its own workflow template and parameterize it properly 

CASMINST-5657

# Checklist

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [X] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

### CODE REVIEW

**Review by leliasen-hpe — APPROVED** [review]

**Comment by rustydb** [comment]
Would recommend rebase and merge vs squash and merge as there are numerous standalone commits.

**Comment by leliasen-hpe** [comment]
This should NOT go in. Further testing is needed on this branch.

**Review by leliasen-hpe — CHANGES_REQUESTED** [review]
I accidentally requested changes here when I thought this was a different PR. I am going to approve this PR again.

**Review by leliasen-hpe — APPROVED** [review]

**Comment by Srinivas-Anand-HPE** [comment]
@rustydb  This PR merges other content from release/1.6 branch to update code in feature/iuf-improvements-1.6.1 along with iuf JIRA CASMINST-5657 

This is corresponding PR for release/1.6 branch which will be merged later
https://github.com/Cray-HPE/docs-csm/pull/5610

**Pull request merged**
