### PR TITLE
CASMINST-7033: Add hotfix reference to 1.5.{1,2} upgrade instructions

### PR DESCRIPTION
**Pull request by haasken-hpe**
# Description

A hotfix is required to fix the functionality of the `update-mgmt-ncn-cfs-config.sh` script in the CSM 1.5.1 and 1.5.2 patch installation instructions. Add a reference to this patch, instructing the admin to install the hotfix before proceeding with the next step.

# Dependencies

- [x] This depends on the creation of the hotfix (see Cray-HPE/csm-hotfixes#60) and the associated field notice. **PLEASE DO NOT MERGE UNTIL THIS IS DONE**

# Checklist

- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

### CODE REVIEW

**Comment by haasken-hpe** [comment]
This change is ready for review, but I created it as a draft PR to ensure it's not merged before the hotfix (Cray-HPE/csm-hotfixes#60) and associated field notice is published.

**Comment by haasken-hpe** [comment]
Test results here: https://gist.github.com/haasken-hpe/6d2918e257aa90043b50b8848ca1f2f1

**Review by shivaprasad-metimath — APPROVED** [review]

**Review by annapoorna-s-alt — APPROVED** [review]

**Comment by haasken-hpe** [comment]
Rebased on latest release/1.5 branch. Unfortunately, I'm still waiting on the field notice to be created before I can merge. See [CSM Hot Fix Tracking](https://rndwiki-pro.its.hpecorp.net/display/CSMTemp/CSM+Hotfix+Tracking) page for status.

**Comment by haasken-hpe** [comment]
The customer advisory was published [here](https://support.hpe.com/hpesc/docDisplay?docId=emr_na-a00144661en_us), and I have updated this PR to reference that customer advisory 🎉 

This is ready to merge whenever, @rustydb or @mtupitsyn.

**Review by rustydb — APPROVED** [review]

**Pull request merged**
