### PR TITLE
CASMINST-5049: Automation: Create Script to deploy kyverno/policies

### PR DESCRIPTION
**Pull request by pradeepkumargl**
CASMINST-5049: AUTOMATION: Create Script to deploy kyverno/policies and run in a stage of prerequisites.sh

Signed-off-by: pradeepkumargl <80017325+pradeepkumargl@users.noreply.github.com>

First cut test logs are attached.

[prerequsites log.txt](https://github.com/Cray-HPE/docs-csm/files/9266422/prerequsites.log.txt)

### CODE REVIEW

**Review by dzou-hpe — APPROVED** [review]

**Review by bo-quan — APPROVED** [review]

**Review by rustydb — APPROVED** [review]
Letting Dennis merge.

**Comment by pradeepkumargl** [comment]
[upgradeTestLogsForKyverno.txt](https://github.com/Cray-HPE/docs-csm/files/9291752/upgradeTestLogsForKyverno.txt)
Upgrade Test logs for Kyverno.

**Comment by yarlagadda-srinivasa-rao** [comment]
We have attached and verified the CSM upgrade test logs. No failures and all looks good. The PR is ready to merge.

**Comment by yarlagadda-srinivasa-rao** [comment]
Policy report shows all pass, at the end when all workers are upgraded.
ncn-m002:~/M001-Backup # kubectl get polr -A
NAMESPACE           NAME                        PASS   FAIL   WARN   ERROR   SKIP   AGE
argo                polr-ns-argo                0      0      0      0       0      3d2h
ceph-cephfs         polr-ns-ceph-cephfs         0      0      0      0       0      3d2h
ceph-rbd            polr-ns-ceph-rbd            0      0      0      0       0      3d2h
cert-manager-init   polr-ns-cert-manager-init   0      0      0      0       0      11h
cert-manager        polr-ns-cert-manager        0      0      0      0       0      3d2h
gatekeeper-system   polr-ns-gatekeeper-system   0      0      0      0       0      3d2h
hnc-system          polr-ns-hnc-system          0      0      0      0       0      10h
istio-operator      polr-ns-istio-operator      0      0      0      0       0      12h
istio-system        polr-ns-istio-system        0      0      0      0       0      3d10h
kyverno             polr-ns-kyverno             0      0      0      0       0      3d2h
metallb-system      polr-ns-metallb-system      0      0      0      0       0      3d8h
nexus               polr-ns-nexus               0      0      0      0       0      3d10h
opa                 polr-ns-opa                 0      0      0      0       0      3d2h
operators           polr-ns-operators           0      0      0      0       0      3d9h
pki-operator        polr-ns-pki-operator        0      0      0      0       0      3d2h
services            polr-ns-services            59     0      0      0       0      3d10h
spire               polr-ns-spire               9      0      0      0       0      3d10h
sysmgmt-health      polr-ns-sysmgmt-health      0      0      0      0       0      3d8h
user                polr-ns-user                0      0      0      0       0      7h49m
vault               polr-ns-vault               0      0      0      0       0      3d2h
velero              polr-ns-velero              0      0      0      0       0      3d2h

**Comment by rustydb** [comment]
@pradeepkumargl it looks like this PR is failing a shellcheck gate, can you remediate?

**Pull request merged**
